config/routes.rb
Rails.application.routes.draw do
  root to: "csvs#new"
  resources :csvs, :only => [:new, :create, :index, :show]
  resources :keywords, :only => [:show]
  resources :reports, :only => [:new, :create, :index, :show]
  resources :urls, :only => [:index]
  mount Resque::Server.new, at: '/debug/resque'
  devise_for :users

end

app/models/csv.rb
require 'open-uri'
class Csv < ActiveRecord::Base
  belongs_to :user
  has_many :keywords

  def google_search keyword
    Resque.enqueue(GoogleSearchKeyword, :do_search, {id: self.id, keyword: keyword})
  end

end

app/models/keyword.rb
class Keyword < ActiveRecord::Base

  belongs_to :csv
  has_many :urls

end

app/models/report.rb
class Report < ActiveRecord::Base
  belongs_to :user
end

app/models/url.rb
class Url < ActiveRecord::Base

  belongs_to :keyword
  enum url_type: [TOP_AD, BOTTOM_AD, NON_AD]

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :csvs
  has_many :reports
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception
  before_action :authenticate_user!

end

app/controllers/csvs_controller.rb
class CsvsController < ApplicationController

  def new
  end

  def create
    f_name, f_data = read_csv params[:csv][:file]
    csv = Csv.create(user_id: current_user.id, filename: f_name)
    f_data.flatten.each do |kw|
      csv.google_search kw
    end
    redirect_to csvs_path, notice: "CSV is being processed, Please click to View."
  end

  def index
    @all_csvs = Csv.all.order(id: :desc).includes(:user)
  end

  def show
    @csv = Csv.find params[:id].to_i
    @keywords = @csv.keywords
  end

  private
  def read_csv file
    csv_data = CSV.read(file.path)
    csv_name = file.original_filename
    return csv_name, csv_data
  end

end

app/controllers/keywords_controller.rb
class KeywordsController < ApplicationController

  def show
    @keyword = Keyword.find params[:id].to_i
    @keyword_urls = @keyword.urls.order(:url_type)
  end

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController

  def new
  end

  def create
    timestamp = DateTime.now
    filename, report_data = generate_report_csv timestamp
    Report.create(user_id: current_user.id, title: filename, data: report_data)
  end

  def index
    @reports = Report.all.order(id: :desc).includes(:user)
  end

  def show
    @report = Report.find params[:id]
    @headers = @report.data["0"].keys.map!(&:humanize)
    @data = @report.data.except!("0")
  end

  private

  def generate_report_csv timestamp
    filename = "keyword-report-#{timestamp}"
    base_qry = Keyword.joins('LEFT JOIN csvs ON csvs.id=keywords.csv_id')
                      .select("keywords.id as keyword_id, csvs.id as csv_id, csvs.filename as csv_filename, keywords.word as keyword, keywords.no_of_ads_top, keywords.no_of_ads_bottom, keywords.no_of_total_ads, keywords.no_of_non_ads, keywords.no_of_links, keywords.total_results, keywords.created_at")
    query = base_qry.reorder(word: :asc).references(:csv).to_sql
    response.headers["Cache-Control"] = "no-cache"
    response.headers["Content-Type"] = "text/csv; charset=utf-8"
    response.headers["Content-Disposition"] =  %(attachment; filename="#{filename}")
    response.headers["Last-Modified"] = Time.zone.now.ctime.to_s
    conn = ActiveRecord::Base.connection.raw_connection
    full_data = []
    conn.copy_data("COPY (#{query}) TO STDOUT WITH (FORMAT CSV, HEADER TRUE, FORCE_QUOTE *, ESCAPE E'\\\\');") do
       while row = conn.get_copy_data
        response.stream.write row
        ret_hash = row_to_hash row
        full_data<<ret_hash
       end
     end
     response.stream.close
     full_hash = {}
     full_data.each_with_index {|val,index| full_hash[index]=val}
     return filename, full_hash.as_json
  end

  def row_to_hash row
    val_array = row.split(',')
    headers = ['keyword_id', 'csv_id', 'filename', 'word', 'no_of_ads_top', 'no_of_ads_bottom', 'no_of_total_ads', 'no_of_non_ads', 'no_of_links', 'no_of_total_results', 'created_at']
    val_hash = {}
    headers.each_with_index do |h, i|
      val_hash[h.to_sym] = val_array[i]
    end
    val_hash
  end

end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController

  def index
    @q = Url.ransack(params[:q])
    @results = @q.result.includes(:keyword)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/csvs/create.html.erb
<h4>
  File Uploaded
</h4>

app/views/csvs/index.html.erb
<h4>
  List of Uploaded CSV's
</h4>

<table>
  <tr>
    <th>CSV ID</th>
    <th>FILE NAME</th>
    <th>UPLOADED BY</th>
    <th>UPLOADED AT</th>
    <th>VIEW</th>
  </tr>
  <% @all_csvs.each do |csv| %>
    <tr>
    <td><%= csv.id %></td>
    <td><%= csv.filename %></td>
    <td><%= csv.user.email %></td>
    <td><%= csv.created_at %></td>
    <td><%= button_to "VIEW", csv_path(csv), method: :get, class: "button btnFade btnRed btnSmall" %></td>
    </tr>
  <% end %>
</table>

app/views/csvs/new.html.erb
<%= form_for(:csv, :url=>{:action=>"create"}, :html => { :multipart => true }) do |f| %>
<table>
  <tr>
    <td>
      <b><h4>Select a csv file to update google search data:</b></h4><br>
    </td>
  </tr>
  <tr>
    <td>
      <%= f.file_field :file%>
    </td>
  </tr>
  <tr>
    <td>
      <%= f.submit "Submit", class: "button btnFade btnRed" %>
    </td>
  </tr>
</table>
<% end %>

app/views/csvs/show.html.erb
<h4>
  CSV Summary
</h4>
<table>
  <tr>
    <td><b>ID</b></td>
    <td><%= @csv.id %></td>
  </tr>
  <tr>
    <td><b>FILE NAME</b></td>
    <td><%= @csv.filename %></td>
  </tr>
  <tr>
    <td><b>UPLOADED BY</b></td>
    <td><%= @csv.user.email %></td>
  </tr>
  <tr>
    <td><b>UPLOADED AT</b></td>
    <td><%= @csv.created_at %></td>
  </tr>
</table>

<h5>Keywords in CSV</h5>
<table>
  <tr>
    <th>KEYWORD ID</th>
    <th>KEYWORD</th>
    <th>TOTAL RESULTS</th>
    <th>CREATED AT</th>
    <th>VIEW</th>
  </tr>
  <% @keywords.each do |kw| %>
    <tr>
    <td><%= kw.id %></td>
    <td><%= kw.word %></td>
    <td><%= kw.total_results %></td>
    <td><%= kw.created_at %></td>
    <td><%= button_to "VIEW RESULTS", keyword_path(kw), method: :get, class: "button btnFade btnRed btnSmall" %></td>
    </tr>
  <% end %>
</table>

app/views/keywords/show.html.erb
<h4>
  Keyword Summary
</h4>
<div>
  <table>
    <tr>
      <td>ID</td>
      <td><%= @keyword.id %></td>
    </tr>
    <tr>
      <td>KEYWORD</td>
      <td><%= @keyword.word %></td>
    </tr>
    <tr>
      <td>NUMBER OF ADS ON TOP</td>
      <td><%= @keyword.no_of_ads_top %></td>
    </tr>
    <tr>
      <td>NUMBER OF ADS ON BOTTOM</td>
      <td><%= @keyword.no_of_ads_bottom %></td>
    </tr>
    <tr>
      <td>NUMBER OF TOTAL ADS</td>
      <td><%= @keyword.no_of_total_ads %></td>
    </tr>
    <tr>
      <td>NUMBER OF NON AD RESULTS</td>
      <td><%= @keyword.no_of_non_ads %></td>
    </tr>
    <tr>
      <td>NUMBER OF TOTAL LINKS ON PAGE</td>
      <td><%= @keyword.no_of_links %></td>
    </tr>
    <tr>
      <td>TOTAL RESULTS</td>
      <td><%= @keyword.total_results %></td>
    </tr>
    <tr>
      <td>SEARCHED AT</td>
      <td><%= @keyword.created_at %></td>
    </tr>
  </table>
</div>
<h5>Keyword Urls</h5>
<table>
  <tr>
    <th>URL ID</th>
    <th>URL TYPE</th>
    <th>URL LINK</th>
  </tr>
  <% @keyword_urls.each do |url| %>
    <tr>
    <td><%= url.id %></td>
    <td><%= url.url_type %></td>
    <td><%= url.url_link %></td>
    </tr>
  <% end %>
</table>

app/views/layouts/_footer.html.erb
<footer class="footer-row">
	<div class="footer-right">
		<a href="#"><i class="fa fa-facebook"></i></a>
		<a href="#"><i class="fa fa-twitter"></i></a>
		<a href="#"><i class="fa fa-linkedin"></i></a>
		<a href="#"><i class="fa fa-github"></i></a>
	</div>
	<div class="footer-left">
		<p class="footer-links">
			<%= link_to "Home", csvs_path, class: 'link-1' %>
			<%= link_to "CSVs", csvs_path %>
			<%= link_to "Reports", reports_path %>
		  <%= link_to "Query", urls_path %>
			<a href="#">Faq</a>
			<a href="#">Contact</a>
    </p>
		<p>Google Search Keyword App &copy; <%= Time.now.year %></p>
	</div>
</footer>

app/views/layouts/_navbar.html.erb
<div class="contain-to-grid sticky">
  <nav class="top-bar" data-topbar role="navigation">
    <ul class="title-area">
      <li class="name">
        <h1><b><%= link_to "Google Search Keyword App", csvs_path %></b></h1>
      </li>
    </ul>
    <section class="top-bar-section">
        <ul class="right">
        <li class="has-dropdown">
          <a href="#">CSV</a>
          <ul class="dropdown">
            <li><%= link_to "View CSV Data", csvs_path %></li>
            <li><%= link_to "View Keywords Data", csvs_path %></li>
            <li><%= link_to "Upload a new CSV", new_csv_path %></li>
          </ul>
        </li>
        <li class="has-dropdown">
          <a href="#">Reports</a>
          <ul class="dropdown">
            <li><%= link_to "Create a New Report", new_report_path %></li>
            <li><%= link_to "View Past Reports", reports_path %></li>
            <li><%= link_to "Query Data", urls_path %></li>
          </ul>
        </li>
        <li class="has-dropdown">
          <a href="#">Settings</a>
          <ul class="dropdown">
            <li><a href="#">Profile Info</a></li>
            <li><%= link_to "Logout", destroy_user_session_path, :method => :delete %></li>
          </ul>
        </li>
      </ul>
    </section>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Google Search Keyword App" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <div class='container' id="<%= controller.controller_name %>-container">
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>

      <%= yield %>
    </div>

    <%= render 'layouts/footer' %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/reports/create.html.erb
<h4>
  Report created
</h4>

app/views/reports/index.html.erb
<h4>
  All Past Reports
</h4>

<table>
  <tr>
    <th>REPORT ID</th>
    <th>FILE NAME</th>
    <th>UPLOADED BY</th>
    <th>UPLOADED AT</th>
    <th>VIEW</th>
  </tr>
  <% @reports.each do |report| %>
    <tr>
    <td><%= report.id %></td>
    <td><%= report.title %></td>
    <td><%= report.user.email %></td>
    <td><%= report.created_at %></td>
    <td><%= button_to "VIEW", report_path(report), method: :get, class: "button btnFade btnRed btnSmall" %></td>
    </tr>
  <% end %>
</table>

app/views/reports/new.html.erb
<h4>
  Create and download a new report
</h4>
<%= button_to "Create new Report", reports_path, method: :post, class: "button btnFade btnRed" %>

app/views/reports/show.html.erb
<h4>
  Report on <%= @report.created_at %>
</h4>
<table>
  <tr>
    <% @headers.each do |h| %>
      <th><%= h %></th>
    <% end %>
  </tr>
  <% @data.each do |i, dp| %>
    <tr>
      <% dp.each do |k, v| %>
        <td><%= v.gsub('"','') %></td>
      <% end %>
    </tr>
  <% end %>
</table>

app/views/urls/_results.html.erb
<div>
  Total results : <%= @results.size %>
</div>
<table>
  <thead>
    <tr>
      <th><%= sort_link(@q, :url_link) %></th>
      <th>Keyword</th>
      <th>Created at</th>
    </tr>
  </thead>
  <tbody>
    <% @results.each do |result| %>
      <tr>
        <td><%= result.url_link %></td>
        <td><%= result.keyword.word %></td>
        <td><%= result.created_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/urls/index.html.erb
<h4>
  Query Data
</h4>
<%= search_form_for @q do |f| %>
  <%= f.label :url_link_cont %>
  <%= f.search_field :url_link_cont %>
  <%= f.submit class: "button btnFade btnRed" %>
<% end %>
<%= render 'results'%>